name: archetype
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.28
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  postgres:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  api:
    image: ghcr.io/archetype-pal/backend:latest
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    env_file: env_file
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres
  frontend:
    image: ghcr.io/archetype-pal/frontend:dev
    env_file: env_file
    volumes:
      - ./frontend:/src
    depends_on:
      - api
  image_server:
    image: daschswiss/sipi
    ports:
      - 1024:1024
    volumes:
      - ./storage/media:/sipi/images
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    env_file: env_file
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - ./certs:/etc/nginx/certs:ro
      - ./html:/var/www/certbot:ro
    depends_on:
      - api
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./html:/var/www/certbot
      - ./logs:/var/log/letsencrypt
    depends_on:
      - nginx
  ftp:
    image: fauria/vsftpd
    restart: always
    env_file: env_file
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:  # make sure to update archetype_user below to match the user in the env_file 
      - ./storage/media:/home/vsftpd/archetype_user
  
volumes:
  postgres:
  logs:
  elasticsearch_data:
